// jobData.js

export const fakeJobList = [
  {
    id: 0,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: '前端开发工程师',
    salary: '20-40k',
    company: '签程无忧电子科技公司',
    location: '上海市',
    experience: '3-5 年',
    education: '本科',
    matchScore: '92分',
    description: '招聘对象：2025年可拿毕业证国内本硕学生+2024年9月-2025年9月可拿毕业证海外本硕留学生（实习时长最低2个月，最长可任选从2024年6月延续到拿毕业证）\n' +
      '任职要求：1、计算机、软件、通信、数学、自动化等相关专业优先；\n' +
      '2、热爱研发，基础扎实，熟练掌握但不限Java/go/C++/C/Python等编程语言中的一种或数种，有良好的编程习惯；\n' +
      '3、认可签程无忧文化，具备独立工作能力、善于沟通，热衷新技术；\n' +
      '4、优选条件：\n' +
      '（1）熟悉TCP/IP协议及互联网常见应用和协议的原理；\n' +
      '（2）不满足课堂所学，在校期间积极参加校内外软件编程大赛；\n' +
      '\n' +
      '岗位福利：免费夜宵、班车，周二运动日，研究所多样兴趣社团，工作之余碰撞同好~\n',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '李明',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '',
    checked: false
  },
  {
    id: 1,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: '前端开发工程师',
    salary: '20-40k',
    company: 'A公司',
    location: '上海市',
    experience: '3-5 年',
    education: '本科',
    matchScore: '89分',
    description: '这里是职位描述...',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '李明',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '签约成功',
    checked: false
  },
  {
    id: 2,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: 'B公司后端',
    salary: '12-30k',
    company: '签程无忧电子科技公司',
    location: '上海市',
    experience: '3-5 年',
    education: '本科',
    matchScore: '92分',
    description: '这里是职位描述...',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '李明',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '喜欢',
    checked: false
  },
  {
    id: 3,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: 'C公司前端',
    salary: '2-4k',
    company: '签程无忧电子科技公司',
    location: '上海市',
    experience: '3-5 年',
    education: '本科',
    matchScore: '92分',
    description: '这里是职位描述...',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '77',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '已投递',
    checked: false
  },
  {
    id: 4,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: 'DD公司科学家助理',
    salary: '1-3k',
    company: '签程无忧电子科技公司',
    location: '浙江省·杭州市·上城区',
    experience: '3-5 年',
    education: '本科',
    matchScore: '44分',
    description: '这里是职位描述...',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '李明',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '被拒绝',
    checked: false
  },
  {
    id: 5,
    workTime: '3天/周 3个月',
    tags: ['JavaScript', 'Vue.js', 'HTML/CSS'],
    title: 'FFF团火葬岗',
    salary: '20-40k',
    company: '签程无忧电子科技公司',
    location: '北京市',
    experience: '3-5 年',
    education: '本科',
    matchScore: '12分',
    description: '这里是职位描述...',
    hrAvatar: 'https://via.placeholder.com/64',
    hrName: '李明',
    hrPosition: 'HR Manager',
    companyLogo: 'https://via.placeholder.com/32',
    lastActiveTime: '2024年3月27日',
    state: '',
    checked: false
  }
]
